/* Task 1: How many stores does the business have and in which countries? */
SELECT COUNTRY_CODE, COUNT(DISTINCT(INDEX,COUNTRY_CODE)) AS TOTAL FROM DIM_STORE_DETAILS GROUP BY COUNTRY_CODE;
/* Task 2: Which locations currently have the most stores? */
SELECT LOCALITY, COUNT(DISTINCT(INDEX,LOCALITY)) AS TOTAL FROM DIM_STORE_DETAILS GROUP BY LOCALITY ORDER BY TOTAL DESC;
/* Task 3: Which months produce the average highest cost of sales typically? */
SELECT MNTH, SUM(TOTAL_PRICE) AS TOTAL_SALES FROM (SELECT (P.PRODUCT_PRICE * O.PRODUCT_QUANTITY) AS TOTAL_PRICE, dt."month" AS MNTH
FROM ORDERS_TABLE AS O 
INNER JOIN DIM_PRODUCTS AS P ON O.PRODUCT_CODE = P.PRODUCT_CODE 
INNER JOIN DIM_DATE_TIMES AS DT ON DT.DATE_UUID = O.DATE_UUID) AS TOTAL
GROUP BY MNTH ORDER BY TOTAL_SALES DESC
/* Task 4: How many sales are coming from online? */
SELECT LOCATION, COUNT(ID) AS NUMBER_OF_SALES, SUM(QUANTITY) AS PRODUCT_QUANTITY_COUNT FROM
(SELECT O.INDEX AS ID,O.PRODUCT_QUANTITY AS QUANTITY, CASE WHEN ST.LOCALITY = 'N/A' THEN 'WEB' WHEN ST.LOCALITY != 'N/A' THEN 'OFFLINE' END AS LOCATION
FROM ORDERS_TABLE AS O INNER JOIN DIM_STORE_DETAILS AS ST ON ST.STORE_CODE = O.STORE_CODE) AS DATA
GROUP BY LOCATION
/* Task 5: What percentage of sales come through each type of store? */
SELECT S_TYPE as Store_Type, SUM(TOTAL_PRICE) as Total_Sales, (COUNT(CAST(TOTAL_PRICE AS FLOAT)) /(SELECT CAST(COUNT(*) AS FLOAT) FROM ORDERS_TABLE) * 100) as Percentage_Total 
FROM
(SELECT O.INDEX AS ID, P.PRODUCT_PRICE * O.PRODUCT_QUANTITY AS TOTAL_PRICE, ST.STORE_TYPE AS S_TYPE
FROM ORDERS_TABLE AS O 
INNER JOIN DIM_STORE_DETAILS AS ST ON ST.STORE_CODE = O.STORE_CODE
INNER JOIN DIM_PRODUCTS AS P ON P.PRODUCT_CODE = O.PRODUCT_CODE) AS TOTAL
GROUP BY S_TYPE
ORDER BY Total_Sales DESC
/* Task 6: Which month in each year produced the highest cost of sales? */
SELECT MNTH,YEAR, SUM(TOTAL_PRICE) AS TOTAL_SALES FROM (SELECT (P.PRODUCT_PRICE * O.PRODUCT_QUANTITY) AS TOTAL_PRICE, dt."month" AS MNTH, DT."year" as YEAR
FROM ORDERS_TABLE AS O 
INNER JOIN DIM_PRODUCTS AS P ON O.PRODUCT_CODE = P.PRODUCT_CODE 
INNER JOIN DIM_DATE_TIMES AS DT ON DT.DATE_UUID = O.DATE_UUID) AS TOTAL
GROUP BY MNTH,YEAR ORDER BY TOTAL_SALES DESC
/* Task 7: What is our staff headcount?*/
SELECT COUNTRY_CODE, SUM(STAFF_NUMBERS) AS TOTAL FROM DIM_STORE_DETAILS GROUP BY COUNTRY_CODE;
/* Task 8: Which German store type is selling the most? */
SELECT COUNTRY_CODE, STORE_TYPE, SUM(SALE) AS TOTAL_SALES
FROM (SELECT O.INDEX, ST.COUNTRY_CODE,ST.STORE_TYPE, P.PRODUCT_PRICE * O.PRODUCT_QUANTITY AS SALE FROM ORDERS_TABLE AS O
INNER JOIN DIM_STORE_DETAILS AS ST ON ST.STORE_CODE = O.STORE_CODE
INNER JOIN DIM_PRODUCTS AS P ON P.PRODUCT_CODE = O.PRODUCT_CODE
WHERE COUNTRY_CODE = 'DE') AS GERMAN_ORDERS
GROUP BY COUNTRY_CODE, STORE_TYPE
ORDER BY TOTAL_SALES
/* Task 9: How quickly is the company making sales? */
SELECT YEAR, AVG(DIFFERENCE) AS ACTUAL_TIME_TAKEN FROM(
	SELECT NEXT_INTERVAL - TIMESTAMP AS DIFFERENCE, YEAR FROM (
		SELECT TIMESTAMP, LEAD(TIMESTAMP,1) OVER(ORDER BY YEAR,TIMESTAMP) AS NEXT_INTERVAL, YEAR FROM
		(SELECT CAST(CONCAT(YEAR,'-',MONTH,'-',DAY,' ',TIMESTAMP) AS TIMESTAMP) AS TIMESTAMP,YEAR 
		 FROM DIM_DATE_TIMES ) 
		AS ORDERED_TIME ) 
	AS LEAD_TIME)AS AVERAGE
	GROUP BY YEAR ORDER BY ACTUAL_TIME_TAKEN DESC
